# Generated by Django 6.1 on 2026-08-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_group', models.SlugField(help_text="Same value across all language versions of one post, e.g. 'comfort-games'.", max_length=100)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'Français'), ('ja', '日本語')], max_length=2)),
                ('category', models.CharField(choices=[('games', 'Video Games'), ('gamedev', 'Game Development'), ('books', 'Books'), ('growth', 'Personal Growth'), ('cooking', 'Cooking'), ('random', 'Random')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('excerpt', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('translation_group', 'language')},
            },
        ),
    ]
